CREATE DATABASE db_generation_game_online;
use db_generation_game_online;

CREATE TABLE tb_classe(
ID 				BIGINT PRIMARY KEY AUTO_INCREMENT,
CLASSE			VARCHAR(20),
DATA_CADASTRO	DATETIME DEFAULT NOW(),
ATIVO 			BOOL default 0
);


CREATE TABLE tb_personagem(
ID 			BIGINT PRIMARY KEY auto_increment,
NOME		VARCHAR(100),
ATAQUE		INT,
DEFESA      INT,
DATA_CADASTRO	DATETIME DEFAULT NOW(),
ID_CLASSE	bigint,
ATIVO 			BOOL default 0,
constraint FK_PERSON_CLASS FOREIGN KEY (id_classe) REFERENCES tb_classe(ID) 
);

INSERT INTO TB_CLASSE(CLASSE,ATIVO)
values('MAGO',1);
INSERT INTO TB_CLASSE(CLASSE,ATIVO)
values('CRUZADOR',1);
INSERT INTO TB_CLASSE(CLASSE,ATIVO)
values('DRAGÃO',1);
INSERT INTO TB_CLASSE(CLASSE,ATIVO)
values('Guerreiro',1);
INSERT INTO TB_CLASSE(CLASSE,ATIVO)
values('Bardos',1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ID_CLASSE,ATIVO)
VALUES('DARK MAGICIAN',2500,2000,1,1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ID_CLASSE,ATIVO)
VALUES('HEAVY SAMURAI',1800,2000,2,1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ID_CLASSE,ATIVO)
VALUES('Black Dragon Red Eyes',2400,2000,3,1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ID_CLASSE,ATIVO)
VALUES('White Dragon Blue Eyes',3000,2500,3,1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ID_CLASSE,ATIVO)
VALUES('Photon Dragon Eyes Galaxy',3000,2000,3,1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ID_CLASSE,ATIVO)
VALUES('Buster Blade',2800,2500,4,1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ID_CLASSE,ATIVO)
VALUES('Number:39 Utopia',2500,2000,4,1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ATIVO)
VALUES('Sliffer Sky Dragon',4000,4000,1);

INSERT INTO tb_personagem(NOME,ATAQUE,DEFESA,ATIVO)
VALUES('Obelisk the artomentor',4000,4000,1);

SELECT * FROM TB_PERSONAGEM WHERE ATAQUE >2000;

SELECT * FROM TB_PERSONAGEM WHERE DEFESA BETWEEN 1000 AND 2000;

SELECT * FROM TB_PERSONAGEM WHERE NOME LIKE '%C%';

SELECT P.NOME,C.CLASSE
FROM TB_PERSONAGEM P
			JOIN TB_CLASSE C ON P.ID_CLASSE = C.ID;
            
SELECT P.NOME,C.CLASSE
FROM TB_PERSONAGEM P
			JOIN TB_CLASSE C ON P.ID_CLASSE = C.ID AND C.CLASSE='DRAGÃO';

SELECT P.NOME,C.CLASSE
FROM TB_PERSONAGEM P
			JOIN TB_CLASSE C ON P.ID_CLASSE = C.ID
WHERE  C.CLASSE='DRAGÃO';