CREATE DATABASE db_construindo_a_nossa_vida;
USE db_construindo_a_nossa_vida;

CREATE TABLE TB_CATEGORIA(
ID 			bigint PRIMARY KEY auto_increment,
CATEGORIA	VARCHAR(50),
ATIVO		BOOLEAN DEFAULT 1
);

INSERT INTO tb_categoria(CATEGORIA)
VALUES('Liquido'),('Areia'),('Piso'),('CASA'),('AP');

create table TB_PRODUTOS(
ID 				bigint PRIMARY KEY auto_increment,
NOME	    	VARCHAR(100),
VALIDADE		DATE DEFAULT '20220712',
QTDE			INT,
preco			decimal(10,2),
ATIVO			BOOLEAN	DEFAULT 1,
ID_CATEGORIA	BIGINT,
CONSTRAINT FK_PRODUTOS_CATEGORIA FOREIGN KEY (ID_CATEGORIA) references TB_CATEGORIA(ID) 
);

INSERT INTO tb_produtos(NOME,QTDE,ID_CATEGORIA,preco)
VALUES('CIMENTO',8,2,10.5),('VASOLIT',8,2,20.5),('CERAMICA',50,3,40),
('CONTRA-PISO',50,3,50),('TINTA',1,1,120),('ARGAMASSA',8,2,70),
('Caixa dagua',1,1,300),('Torneira',1,1,10);


SELECT * FROM tb_produtos WHERE PRECO > 50;
SELECT * FROM tb_produtos WHERE PRECO BETWEEN 3 AND 60;
select * from tb_produtos WHERE NOME LIKE '%C%'; 

SELECT *
FROM TB_PRODUTOS P
	JOIN TB_CATEGORIA C ON P.ID_CATEGORIA=C.ID;

SELECT *
FROM TB_PRODUTOS P
	JOIN TB_CATEGORIA C ON P.ID_CATEGORIA=C.ID
WHERE C.CATEGORIA='AREIA';