CREATE DATABASE db_cursoDaMinhaVida;
USE db_cursoDaMinhaVida;

CREATE TABLE TB_CATEGORIA(
ID 			bigint PRIMARY KEY auto_increment,
CATEGORIA	VARCHAR(50),
ATIVO		BOOLEAN DEFAULT 1
);

INSERT INTO tb_categoria(CATEGORIA)
VALUES('PRESENCIAL'),('ONLINE'),('SEMI-PRESENCIAL'),('GRAVADA'),('EVENTO');

create table TB_PRODUTOS(
ID 				bigint PRIMARY KEY auto_increment,
NOME	    	VARCHAR(100),
preco			decimal(10,2),
ATIVO			BOOLEAN	DEFAULT 1,
ID_CATEGORIA	BIGINT,
CONSTRAINT FK_PRODUTOS_CATEGORIA FOREIGN KEY (ID_CATEGORIA) references TB_CATEGORIA(ID) 
);

INSERT INTO tb_produtos(NOME,ID_CATEGORIA,preco)
VALUES('JAVA BASICO A AVANCADO',2,1200),('ASP.NET 5 AVANCADO',2,1200),('PHP PRA QUEM TEM PRESSA',1,2500),
('JAVASCRIPT INICIANTE',1,500),('TADS - TEC ANALISE DESENVOLVIMENTO',3,6000),('COBOL PARA MESTRES',4,4000),
('AWS CERTIFICATED INTRO',5,0),('GOOGLE CLOUD',5,0);


SELECT * FROM tb_produtos WHERE PRECO > 50;
SELECT * FROM tb_produtos WHERE PRECO BETWEEN 3 AND 60;
select * from tb_produtos WHERE NOME LIKE '%j%'; 

SELECT *
FROM TB_PRODUTOS P
	JOIN TB_CATEGORIA C ON P.ID_CATEGORIA=C.ID;

SELECT *
FROM TB_PRODUTOS P
	JOIN TB_CATEGORIA C ON P.ID_CATEGORIA=C.ID
WHERE C.CATEGORIA='PRESENCIAL';