CREATE DATABASE db_farmacia_do_bem;
USE db_farmacia_do_bem;

CREATE TABLE TB_CATEGORIA(
ID		BIGINT PRIMARY KEY auto_increment,
NOME	VARCHAR(200),
ATIVO	BOOL DEFAULT 1
);


CREATE TABLE TB_PRODUTO (
ID				BIGINT PRIMARY KEY auto_increment,
NOME			VARCHAR(300),
PRECO			DECIMAL(10,2),
QTDEVALIDADE	DATE ,
ESTOQUE	INT,
ID_CATEGORIA	BIGINT,
CONSTRAINT FK_PRODUTO_CATEGORIA foreign key (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID)
);


INSERT INTO TB_CATEGORIA(NOME)
VALUES('ANTIBIOTICO');
INSERT INTO TB_CATEGORIA(NOME)
VALUES('COMPRIMIDO');
INSERT INTO TB_CATEGORIA(NOME)
VALUES('LIQUIDO');

INSERT INTO TB_PRODUTO (NOME,PRECO,QTDEVALIDADE,ID_CATEGORIA,ESTOQUE)
VALUES('ADVIL',7.5,'20220701',2,8);
INSERT INTO TB_PRODUTO (NOME,PRECO,QTDEVALIDADE,ID_CATEGORIA,ESTOQUE)
VALUES('ADVIL',9.5,'20220701',3,5);
INSERT INTO TB_PRODUTO (NOME,PRECO,QTDEVALIDADE,ID_CATEGORIA,ESTOQUE)
VALUES('Amoxicilina',60.0,'20220701',3,4);
INSERT INTO TB_PRODUTO (NOME,PRECO,QTDEVALIDADE,ID_CATEGORIA,ESTOQUE)
VALUES('Ampicilina',80.0,'20220701',3,2);
INSERT INTO TB_PRODUTO (NOME,PRECO,QTDEVALIDADE,ID_CATEGORIA,ESTOQUE)
VALUES('DIPIRONA',7.5,'20220701',2,7);
INSERT INTO TB_PRODUTO (NOME,PRECO,QTDEVALIDADE,ID_CATEGORIA,ESTOQUE)
VALUES('EXPERIMENTAL',1.5,'20220701',3,3);
INSERT INTO TB_PRODUTO (NOME,PRECO,QTDEVALIDADE,ID_CATEGORIA,ESTOQUE)
VALUES('Gardenal',60.0,'20220701',2,1);
INSERT INTO TB_PRODUTO (NOME,PRECO,QTDEVALIDADE,ID_CATEGORIA,ESTOQUE)
VALUES('SalonPass',180.0,'20220701',2,2);


SELECT * FROM TB_PRODUTO WHERE PRECO> 50;

SELECT * FROM TB_PRODUTO WHERE PRECO BETWEEN  3 AND 60;

SELECT * FROM TB_PRODUTO WHERE NOME LIKE '%B%';


SELECT C.NOME,P.NOME AS REMEDIO, P.PRECO,P.ESTOQUE
FROM TB_PRODUTO P 
	JOIN TB_CATEGORIA C ON P.ID_CATEGORIA = C.ID;


SELECT C.NOME,P.NOME AS REMEDIO, P.PRECO,P.ESTOQUE
FROM TB_PRODUTO P 
	JOIN TB_CATEGORIA C ON P.ID_CATEGORIA = C.ID
WHERE C.NOME= 'COMPRIMIDO';