CREATE DATABASE db_pizzaria_legal;
USE db_pizzaria_legal;

CREATE TABLE TB_CATEGORIA(
ID					BIGINT	PRIMARY KEY auto_increment,
TIPO_CATEGORIA		VARCHAR(50),
DISPONIVEL			BOOLEAN	DEFAULT 1
);

INSERT INTO TB_CATEGORIA(TIPO_CATEGORIA)
VALUES ('BROTO');
INSERT INTO TB_CATEGORIA(TIPO_CATEGORIA)
VALUES ('TAMANHO FAMILIA');
INSERT INTO TB_CATEGORIA(TIPO_CATEGORIA)
VALUES ('BORDA RECHEADA');
INSERT INTO TB_CATEGORIA(TIPO_CATEGORIA)
VALUES ('DOCE');
INSERT INTO TB_CATEGORIA(TIPO_CATEGORIA)
VALUES ('SEM BORDA');

CREATE TABLE tb_pizza(
ID 					BIGINT PRIMARY KEY auto_increment,
SABOR				VARCHAR(30) ,
PRECO				decimal(10,2),
DISPONIVEL			BOOLEAN	DEFAULT 1,
ID_CATEGORIA		BIGINT,
constraint FK_CATEGORIA_PIZZA	foreign key (ID_CATEGORIA) references TB_CATEGORIA(ID)
);
SELECT * FROM TB_CATEGORIA;

INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('CALABRESA',25,1);
INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('CALABRESA ESPECIAL',33,2);
INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('PORTUGUESA',33,2);
INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('PEPPERONI',40,2);
INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('FRANGO COM CHEDDAR',33,3);
INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('PEITO DE PERU',33,3);

INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('ROMEU E JULIETA',33,4);
INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('BRIGADEIRO',33,4);
INSERT INTO tb_pizza(SABOR,PRECO,ID_CATEGORIA)
VALUES('MUSSARELA',20,5);


SELECT * FROM TB_PIZZA WHERE PRECO > 45;

SELECT * FROM TB_PIZZA WHERE PRECO BETWEEN 29 AND 60;

SELECT * FROM TB_PIZZA WHERE SABOR LIKE '%C%';

SELECT C.TIPO_CATEGORIA, P.SABOR,P.PRECO
FROM TB_PIZZA P 
	JOIN TB_CATEGORIA C ON P.ID_CATEGORIA = C.ID;


SELECT C.TIPO_CATEGORIA, P.SABOR,P.PRECO
FROM TB_PIZZA P 
	JOIN TB_CATEGORIA C ON P.ID_CATEGORIA = C.ID
WHERE C.TIPO_CATEGORIA = 'DOCE';